version: "2"
linters:
  enable:
    - cyclop
    - err113
    - errname
    - exhaustive
    - exptostd
    - funcorder
    - gocritic
    - revive
    - govet
  exclusions:
    rules:
      # prevent revive for complaining about the "types" package
      - linters:
          - revive
        text: "avoid meaningless package names"
  settings:
    gocritic:
      disabled-checks:
        - ifElseChain
