# fly.toml app configuration file generated for playbot-website on 2024-05-13T18:04:44+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'playbot-website'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
