name: Dev - CI/CD
on:
  pull_request:

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
      - name: Install Protoc
        uses: arduino/setup-protoc@v2
      - name: generate RPC code
        run: make generate
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          skip-pkg-cache: true
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'
    - name: Start MariaDB
      run: docker compose up --detach && sleep 2
    - name: Install Protoc
      uses: arduino/setup-protoc@v2
    - name: generate RPC code
      run: make generate
    - name: Run tests
      run: go test ./...
