name: Dev - CI/CD
on:
  pull_request:
permissions:
  contents: read
  pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
      - name: generate RPC code
        run: make generate
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          skip-pkg-cache: true
  tests:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
    - name: Start MariaDB
      run: docker compose up --detach && sleep 2
    - name: Install Protoc
      uses: arduino/setup-protoc@v3
    - name: Generate RPC code
      run: make generate
    - name: Run tests
      run: go run gotest.tools/gotestsum@v1 --junitfile junit.xml
    - name: Test Report
      uses: dorny/test-reporter@v2
      if: always()
      with:
        name: golang tests
        path: junit.xml
        reporter: java-junit
        fail-on-error: true
